---
.travis.yml:
  docker_sets:
    - set: centos7-64{hostname=centos7-64.example.com}
    - set: centos8-64{hostname=centos8-64.example.com}
    - set: debian8-64{hostname=debian8-64.example.com}
    - set: debian9-64{hostname=debian9-64.example.com}
    - set: debian10-64{hostname=debian10-64.example.com}
    - set: ubuntu1604-64{hostname=ubuntu1604-64.example.com}
    - set: ubuntu1804-64{hostname=ubuntu1804-64.example.com}
  secure: "RlXD9MDfKavdsjPCtq8XmqXTszraam9oFNJlnd+tryJQ/fN10Q8l36+UcSbxUgBF9Wyy8muyjUiLB9bhje1IQUcsATXpa0YgWdoTIhv18SmIA58a1eXt52TqeLG73aSgu2ZCebc9SkSRV+vNVXcPleIdb9dX8HjsJOGk1sw0jGwDO93nSuInKG2/rl0kevbI5BcY6G+o2dInI4Nknq0nxpzcw8X602j/xak95lLxQmQfaMrXvKUAdp4XuLV8YfbahQhD7bCe4b6hudqVi4/I7Xag8SonX9pMZJzC5J0USjDqG01BQLXAz2KDrjmxf7Hy4KI8BIkZonvjE2dx23NRM28HNDhlcMRV6k9p2SSCR5CZKzwRXOh38OBNL/vpHnpTk5GOEqSMwD8Zt0jJpGNIMR6i4a5fcdBznp3FXqc/28gXduAAn2lGBG4lb8AMJ40J5bgmPYJvoYMxrS2rwfFJ91LYk3UK2wNhbGF772+0sRQi0iyOUEoxa3D0Jkt9PrsYXQ6rxW6dNkkZFGdE0Uni6Mm4mNZkWcK2Ke+wRGSetIv2vyABY5LJinBLjYH8T4LZYrmQ/LALuIhjJWhxXvWA94/brwIXF0Nkou9vEKu6uT+bBHbGPrLmvPkLsnHxGV515M0NTUFCQ8coPpYHgacJkpfTP9IZk7QHFUi3LWNG1VI="
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  delete: true
